name: toolz
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.10
  - biopython
  - black
  - cython
  - ipython
  - jupyterlab
  - line_profiler
  - lz4
  - matplotlib
  - matplotlib-venn
  - memory_profiler
  - netCDF4
  - networkx
  - graph-tool
  - nodejs
  - numpy
  - numpyro
  - openpyxl
  - pandas
  - parallel
  - patsy
  - pigz
  - prodigal
  - prokka
  - python-graphviz
  - r-car
  - r-dplyr
  - r-geepack
  - r-vegan
  - rpy2
  - scikit-bio
  - scikit-learn
  - scipy
  - seaborn
  - seqtk
  - snakemake
  - statsmodels
  - tqdm
  - umap-learn
  - xarray
  - xlrd
  - pip
